{
  config,
  lib,
  hostname,
  osConfig ? null,
  ...
}:
let
  niriDir = "${config.my.home.dotfilesDir}/modules/home/programs/wm/niri";
  gsrEnabled =
    if osConfig != null && (osConfig ? my.programs.gpu-screen-recorder.enable) then
      osConfig.my.programs.gpu-screen-recorder.enable
    else
      false;
  easyeffectsEnabled =
    if osConfig != null && (osConfig ? my.programs.easyeffects.enable) then
      osConfig.my.programs.easyeffects.enable
    else
      false;
in

{
  options.my.home.gpu-screen-recorder.autostart = lib.mkOption {
    type = lib.types.bool;
    default = gsrEnabled;
    description = "Autostart GPU Screen Recorder UI overlay in Niri";
  };

  options.my.home.easyeffects.autostart = lib.mkOption {
    type = lib.types.bool;
    default = easyeffectsEnabled;
    description = "Autostart EasyEffects daemon in Niri";
  };

  config = lib.mkIf config.my.home.wm.niri.enable {
    home.file.".config/niri/config.kdl".source =
      config.lib.file.mkOutOfStoreSymlink "${niriDir}/config.kdl";

    home.file.".local/bin/niri-autostart" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        # Auto-generated by Nix for ${hostname}

      ''
      + ''
        # Restore the selected image or video wallpaper after skwd-walld starts.
        WALL="$HOME/.local/state/theme/media"
        [ -e "$WALL" ] || WALL="$HOME/.local/state/theme/wallpaper"
        [ -e "$WALL" ] && skwd-helm apply "$WALL" &
      ''
      + lib.optionalString config.my.home.gpu-screen-recorder.autostart ''

        # GPU Screen Recorder UI overlay
        if ! pgrep -x "gsr-ui" > /dev/null; then
          gsr-ui &
        fi
      ''
      + lib.optionalString config.my.home.easyeffects.autostart ''

        # EasyEffects audio daemon
        if ! pgrep -x "easyeffects" > /dev/null; then
          easyeffects --hide-window --service-mode &
        fi
      '';
    };
  };
}
